---
title: "Combined FCR Chart"
output: 
  html_notebook:
    code_folding: hide
    theme: spacelab
    highlight: tango
    toc: yes
    toc_depth: 2
    toc_float: yes
    df_print: paged
---

# Chart here
The chart that shows FCR ratios for NSE & SE babies, children, and adults. Adults is Hearing Novice & Deaf Early. 


```{r message=FALSE, warning=FALSE}
library(tidyverse)

babies <- read_csv("fcr_chart_babies.csv")
children <- read_csv("fcr_chart_children.csv")

adults <- read_csv("fcr_chart_adults.csv") %>%
  rename(fcr_mean = mean,
         group = maingroup) %>%
  filter(group == 'Deaf Early' | group == 'Hearing Novice') %>%
  mutate(lang = if_else(group == 'Deaf Early', 'SE', 'NSE')) %>%
  mutate(group = 'adults')

df <- bind_rows(babies, children, adults) %>%
  mutate(group = fct_relevel(group, c('babies', 'children', 'adults')))
  
df %>%
  ggplot(aes(x = group, y = fcr_mean, color = direction)) +
  facet_wrap('lang') +
  geom_hline(yintercept = 0, size = 0.5) +
  geom_point(size = 2, position = position_dodge(width = 0.4)) +
  geom_errorbar(aes(ymin = fcr_mean - se, ymax = fcr_mean + se), 
                size = 1, 
                position = position_dodge(0.4), 
                width = 0.3) +
  theme_linedraw() +
  theme(
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        # axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        panel.border = element_rect(size = 1),
        axis.ticks.y = element_line(size = 0.5),
        axis.text.y = element_text(size = 12),
        panel.grid.major.y = element_line(size = 0.5,
                                          color = "light gray",
                                          linetype = "dashed"),
        strip.background = element_blank(),
        strip.text = element_text(color = 'black')) +
  guides(color = FALSE, fill = FALSE)

df %>%
  ggplot(aes(x = group, y = fcr_mean, color = direction)) +
  facet_wrap('lang') +
  geom_hline(yintercept = 0, size = 0.5) +
  geom_point(size = 2, position = position_dodge(width = 0.4)) +
  geom_errorbar(aes(ymin = fcr_mean - se, ymax = fcr_mean + se), 
                size = 1, 
                position = position_dodge(0.4), 
                width = 0.3) +
  theme_linedraw() +
  theme(
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        # axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        panel.border = element_rect(size = 1),
        axis.ticks.y = element_line(size = 0.5),
        axis.text.y = element_text(size = 12),
        panel.grid.major.y = element_line(size = 0.5,
                                          color = "light gray",
                                          linetype = "dashed"),
        strip.background = element_blank(),
        strip.text = element_text(color = 'black')) +
  guides(color = FALSE, fill = FALSE) +
  scale_y_continuous(limits = c(-1, 1))

```

# Regressing FCR on Age

```{r message=FALSE, warning=FALSE}

# Import subject-level data 
babies_indiv <- read_csv("fcr_individual_values_babies.csv") %>%
  mutate(age = age/12)

children_indiv <- read_csv("fcr_individual_values_children.csv")

adults_indiv <- read_csv("fcr_individual_values_adults.csv") %>%
  rename(fcr = facechest,
         group = maingroup,
         name = participant) %>%
  filter(group == 'Deaf Early' | group == 'Hearing Novice') %>%
  mutate(lang = if_else(group == 'Deaf Early', 'SE', 'NSE')) %>%
  mutate(group = 'adults')

# Combine datasets
everybody <- bind_rows(babies_indiv,
                       children_indiv,
                       adults_indiv)

everybody_se <- everybody %>%
  filter(lang == 'SE')

# Plot
everybody_se %>%
  ggplot(aes(x = age, y = fcr, color = direction)) +
  geom_point(alpha = 0.5, size = 2) +
  geom_smooth(method = 'lm', se = F) +
  scale_y_continuous(limits = c(-1, 1)) +
  geom_hline(yintercept = 0, size = 0.5) +
  labs(x = 'Age (Years)',
       y = 'FPI',
       color = 'Video Direction') +
  theme_linedraw() +
    theme(
        panel.grid.minor.y = element_blank(),
        # panel.grid.major.x = element_blank(),
        # axis.title.y = element_blank(),
        # axis.title.x = element_blank(),
        # axis.text.x = element_blank(),
        # axis.ticks.x = element_blank(),
        panel.border = element_rect(size = 1),
        axis.ticks.y = element_line(size = 0.5),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        # panel.grid.major.y = element_line(size = 0.5,
        #                                   color = "light gray",
        #                                   linetype = "dashed"),
        strip.background = element_blank(),
        strip.text = element_text(color = 'black'))


# Regression
age_lm <- lm(data = everybody_se, fcr ~ age * direction)
summary(age_lm)
confint(age_lm)
```

# What about NSE?

```{r message=FALSE, warning=FALSE}

everybody_nse <- everybody %>%
  filter(lang == 'NSE')

# Plot
everybody_nse %>%
  ggplot(aes(x = age, y = fcr, color = direction)) +
  geom_point(alpha = 0.5, size = 2) +
  geom_smooth(method = 'lm', se = F) +
  scale_y_continuous(limits = c(-1, 1)) +
  geom_hline(yintercept = 0, size = 0.5) +
  labs(x = 'Age (Years)',
       y = 'FPI',
       color = 'Video Direction') +
  theme_linedraw() +
    theme(
        panel.grid.minor.y = element_blank(),
        # panel.grid.major.x = element_blank(),
        # axis.title.y = element_blank(),
        # axis.title.x = element_blank(),
        # axis.text.x = element_blank(),
        # axis.ticks.x = element_blank(),
        panel.border = element_rect(size = 1),
        axis.ticks.y = element_line(size = 0.5),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        # panel.grid.major.y = element_line(size = 0.5,
        #                                   color = "light gray",
        #                                   linetype = "dashed"),
        strip.background = element_blank(),
        strip.text = element_text(color = 'black'))


# Regression
age_lm <- lm(data = everybody_nse, fcr ~ age * direction)
summary(age_lm)
confint(age_lm)
```
